In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('csv/sample_sales_data_1M.csv')
df

,Sale_ID,Date,Customer_ID,Product_ID,Product_Name,Category,Quantity,Unit_Price,Region,Salesperson,Total_Price
0,1,2025-06-07,8270,685,Itself,Toys,3,456.18,West,Angel Knight,1368.54
1,2,2024-12-03,1860,175,Talk,Electronics,8,474.02,East,Ms. Heather Roberts,3792.16
2,3,2025-04-06,6390,649,Religious,Toys,6,161.44,West,Nicole Woods,968.64
3,4,2024-06-15,6191,209,Box,Home,9,473.95,East,Isabella Henson,4265.55
4,5,2023-08-01,6734,700,Person,Home,7,343.00,North,Jenny Hernandez,2401.00
...,...,...,...,...,...,...,...,...,...,...,...
999995,999996,2023-11-28,2632,974,Hear,Clothing,9,459.99,South,John Castro,4139.91
999996,999997,2024-01-25,7377,659,Eight,Clothing,1,226.03,East,Rhonda Davis,226.03
999997,999998,2023-11-19,6759,796,Spring,Electronics,9,487.53,East,Eric Nelson,4387.77
999998,999999,2023-09-19,6413,965,According,Clothing,1,222.45,East,Kathleen Davis,222.45
999999,1000000,2023-11-07,7288,209,Special,Electronics,9,210.26,North,Thomas Reyes,1892.34

In [4]:
df.head(10)

,Sale_ID,Date,Customer_ID,Product_ID,Product_Name,Category,Quantity,Unit_Price,Region,Salesperson,Total_Price
0,1,2025-06-07,8270,685,Itself,Toys,3,456.18,West,Angel Knight,1368.54
1,2,2024-12-03,1860,175,Talk,Electronics,8,474.02,East,Ms. Heather Roberts,3792.16
2,3,2025-04-06,6390,649,Religious,Toys,6,161.44,West,Nicole Woods,968.64
3,4,2024-06-15,6191,209,Box,Home,9,473.95,East,Isabella Henson,4265.55
4,5,2023-08-01,6734,700,Person,Home,7,343.00,North,Jenny Hernandez,2401.00
5,6,2024-12-11,7265,187,North,Clothing,8,472.80,North,Lisa Heath,3782.40
6,7,2023-09-06,1466,955,Try,Books,6,392.35,West,William Hernandez,2354.10
7,8,2024-06-12,5426,917,Sister,Electronics,4,399.36,West,Veronica Richardson,1597.44
8,9,2024-10-26,6578,180,Leave,Toys,4,100.05,North,Tara Preston,400.20
9,10,2025-06-10,9322,948,Develop,Clothing,9,65.99,North,Kenneth Salas,593.91

In [5]:
df.tail(10)

,Sale_ID,Date,Customer_ID,Product_ID,Product_Name,Category,Quantity,Unit_Price,Region,Salesperson,Total_Price
999990,999991,2025-04-30,5495,810,Military,Books,8,13.11,North,Eric Nelson,104.88
999991,999992,2024-07-22,1640,319,Although,Home,2,104.89,East,Jennifer Costa,209.78
999992,999993,2024-09-23,3406,743,Last,Books,6,293.21,East,Derrick Jackson,1759.26
999993,999994,2025-02-04,3672,163,Possible,Clothing,7,62.60,West,Lisa Heath,438.20
999994,999995,2023-09-09,8836,266,Hard,Toys,8,86.73,West,Dawn Drake,693.84
999995,999996,2023-11-28,2632,974,Hear,Clothing,9,459.99,South,John Castro,4139.91
999996,999997,2024-01-25,7377,659,Eight,Clothing,1,226.03,East,Rhonda Davis,226.03
999997,999998,2023-11-19,6759,796,Spring,Electronics,9,487.53,East,Eric Nelson,4387.77
999998,999999,2023-09-19,6413,965,According,Clothing,1,222.45,East,Kathleen Davis,222.45
999999,1000000,2023-11-07,7288,209,Special,Electronics,9,210.26,North,Thomas Reyes,1892.34

In [6]:
df["Sale_ID"].dtype

dtype('int64')

In [7]:
df["Total_Price"].dtype

dtype('float64')

In [8]:
df.select_dtypes(include=['number'])

        Sale_ID  Customer_ID  Product_ID  Quantity  Unit_Price  Total_Price
0             1         8270         685         3      456.18      1368.54
1             2         1860         175         8      474.02      3792.16
2             3         6390         649         6      161.44       968.64
3             4         6191         209         9      473.95      4265.55
4             5         6734         700         7      343.00      2401.00
...         ...          ...         ...       ...         ...          ...
999995   999996         2632         974         9      459.99      4139.91
999996   999997         7377         659         1      226.03       226.03
999997   999998         6759         796         9      487.53      4387.77
999998   999999         6413         965         1      222.45       222.45
999999  1000000         7288         209         9      210.26      1892.34

[1000000 rows x 6 columns]

In [9]:
#create new column discounted_price
df2 = pd.DataFrame(df, columns = ['Sale_ID','Customer_ID','Product_ID','Quantity','Unit_Price','Total_Price', 'Discounted_Price_10pct'])

df2

,Sale_ID,Customer_ID,Product_ID,Quantity,Unit_Price,Total_Price,Discounted_Price_10pct
0,1,8270,685,3,456.18,1368.54,NaN
1,2,1860,175,8,474.02,3792.16,NaN
2,3,6390,649,6,161.44,968.64,NaN
3,4,6191,209,9,473.95,4265.55,NaN
4,5,6734,700,7,343.00,2401.00,NaN
...,...,...,...,...,...,...,...
999995,999996,2632,974,9,459.99,4139.91,NaN
999996,999997,7377,659,1,226.03,226.03,NaN
999997,999998,6759,796,9,487.53,4387.77,NaN
999998,999999,6413,965,1,222.45,222.45,NaN
999999,1000000,7288,209,9,210.26,1892.34,NaN

In [14]:
df2['Discounted_Price_10pct'] = df2['Total_Price'] - df2['Total_Price'] * 0.1
df2

,Sale_ID,Customer_ID,Product_ID,Quantity,Unit_Price,Total_Price,Discounted_Price_10pct
0,1,8270,685,3,456.18,1368.54,1231.686
1,2,1860,175,8,474.02,3792.16,3412.944
2,3,6390,649,6,161.44,968.64,871.776
3,4,6191,209,9,473.95,4265.55,3838.995
4,5,6734,700,7,343.00,2401.00,2160.900
...,...,...,...,...,...,...,...
999995,999996,2632,974,9,459.99,4139.91,3725.919
999996,999997,7377,659,1,226.03,226.03,203.427
999997,999998,6759,796,9,487.53,4387.77,3948.993
999998,999999,6413,965,1,222.45,222.45,200.205
999999,1000000,7288,209,9,210.26,1892.34,1703.106

In [15]:
#rename columns
df2.rename(columns={'Discounted_Price_10pct': 'Total_Price_After_Discounted_Price_10pct'}, inplace=True)
df2

,Sale_ID,Customer_ID,Product_ID,Quantity,Unit_Price,Total_Price,Total_Price_After_Discounted_Price_10pct
0,1,8270,685,3,456.18,1368.54,1231.686
1,2,1860,175,8,474.02,3792.16,3412.944
2,3,6390,649,6,161.44,968.64,871.776
3,4,6191,209,9,473.95,4265.55,3838.995
4,5,6734,700,7,343.00,2401.00,2160.900
...,...,...,...,...,...,...,...
999995,999996,2632,974,9,459.99,4139.91,3725.919
999996,999997,7377,659,1,226.03,226.03,203.427
999997,999998,6759,796,9,487.53,4387.77,3948.993
999998,999999,6413,965,1,222.45,222.45,200.205
999999,1000000,7288,209,9,210.26,1892.34,1703.106